name: Build

on:
  push:
    branches:
      - main

jobs:
        
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: mosaic-2
        password: ${{ secrets.FRONT_DOCKER_TOKEN }}
    - 
      name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64/v8
        tags: ghcr.io/mosaic-2/ide-yar-front/ide-yar:latest
